project:
  type: website

website:
  title: "Quarto Blog Demo"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://twitter.com
      - icon: youtube
        href: https://www.youtube.com/
      - icon: envelope
        href: https://myaccount.google.com/
format:
  html:
    #theme: theme.scss
    theme: sandstone
    mainfont: roboto
    fontcolor: "#212529"
    fontsize: 1rem
    monofont: fira code
    css: style.css
    toc: true
    toc-location: left
    toc-expand: 1
    toc-depth: 3

editor: source

